Replace most ToServer instances with a single overlappable instance
anton-k/mig pull request #11
Opened 2023-10-17 20:32 UTC by ambroslins

We can construct a server from every route. However this requires `UndecidableInstances` and a `OVERLAPPABLE` pragma.

Not sure if this is actually better, but it does mean we have to don´t have to define extra instances for the `ToServer` class.

I will just leave this here. Feel free to close it if you don´t like it.

2023-10-18 08:19 UTC, anton-k commented
This is interesting. I need to try it out with examples. As sometimes OVERLAPPABLE-code compiles on the library level. But produces errors on the level of the user code.

2023-10-18 09:10 UTC, ambroslins commented
Yes, I am also not sure whether this might cause problems down the line. I just saw that a instance like this should be possible because the other instances are basically all the same.

Btw. I am really excited about this project and also looking forward to contributing. So if you need help with anything just let me know.

2023-10-19 10:37 UTC, anton-k requested changes
We an also remove that instance from the file `mig-extra/src/Mig/Extra/Server/Json.hs`

2023-10-19 10:39 UTC, anton-k commented
Thank you for support and help poposal. 
I keep file `todo.md` of the things that I'd like to do next.
If you are interested in contribution you can also take some of those items. Some of them are small some of them are really big.

2023-10-19 10:40 UTC, anton-k commented
All examples compile. i think we can merge it.

2023-10-19 12:16 UTC, anton-k approved these changes

2023-10-19 12:17 UTC, merged

2023-10-19 12:17 UTC, anton-k commented
thanks for fix! Merged